---
tags:
- pdep
- guia2
- ordenSuperior
- listas
- pointFree
- aplicacionParcial
layout: input_right
editor: code
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
