---
tags:
- haskell
- funcional
- integrador
- listas
- orden superior
- map
- filter
layout: input_right
editor: code
type: problem
extra_visible: false
manual_evaluation: false
choices: []
name: Cuántas Muzzas
